# ===============================
# COMMON CONFIG (ALL SERVICES)
# ===============================
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# ===============================
# USER-SERVICE CONFIG
# ===============================
---
spring:
  config:
    activate:
      on-profile: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/USERdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

# ===============================
# ACCOUNTSERVICE CONFIG
# ===============================
---
spring:
  config:
    activate:
      on-profile: accountsservice

  datasource:
    url: jdbc:postgresql://localhost:5432/accountServiceDb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

# ===============================
# LOANSERVICE CONFIG
# ===============================
---
spring:
  config:
    activate:
      on-profile: loanservice

  datasource:
    url: jdbc:postgresql://localhost:5432/LoanServiceDb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

# ===============================
# TRANSACTIONSERVICE CONFIG
# ===============================
---
spring:
  config:
    activate:
      on-profile: transactionservice

  datasource:
    url: jdbc:postgresql://localhost:5432/TransacationData
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


